version: 2.1
only_maintainers: &only_maintainers
  filters:
    branches:
      # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
      ignore: /pull\/[0-9]+/

only_branches: &only_branches
  filters:
    branches:
      ignore:
        - main
orbs:
  prodsec: snyk/prodsec-orb@1
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: golang:1.16.2
    steps:
      - checkout
      - run: make release
      - persist_to_workspace:
          root: ~/project
          paths:
            - bin/
  test:
    docker:
      - image: golang:1.16.2
    steps:
      - checkout
      - run: make test-coverage
  release:
    environment:
      CIRCLE_PROJECT_USERNAME: cloudskiff
      CIRCLE_PROJECT_REPONAME: lambda-env-updater
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${CIRCLE_TAG} ${CIRCLE_TAG} ./bin/
  security-scans:
    docker:
      - image: cimg/go:1.16.2
    resource_class: small
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  push:
    jobs:
      - test:
        <<: *only_branches
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-iac
      - security-scans:
          name: Security Scans
          context:
            - analysis-iac
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release:
          context: lambda-env-updater
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
